import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { Retargeter } from './Retargeting.js';
import { CLIP_LIBRARY } from './ClipLibrary.js';

/**
 * The player animation library.
 *
 * The manifest is `js/ClipLibrary.js`, generated by `tools/clip-manifest.mjs`
 * (`npm run clips`): it scans Animations/, classifies every FBX by naming
 * convention, measures each playable clip's real body-frame velocity and
 * vertical drop, and tags it with the features MotionMatching queries.
 *
 * Entry shape (see the generated file for the full convention):
 *   { key, path, group, role, tier, feats: { vx, vz, speed }, duration,
 *     meta?, measured? }
 *
 *   role 'loop'        — locomotion loop, queried by (vx, vz) within its tier
 *   role 'idle-loop'   — the standing / crouched idle (legs + body baseline)
 *   role 'idle-break'  — full-body idle variation (played by the upper layer)
 *   role 'jump-*'      — one-shots addressed by the jump phase machine
 *   role 'transition'  — one-shots (crouch enter/exit)
 *
 * Tiers: 0 idle · 1 walk · 2 run · 3 sprint · 4 crouch.
 */

// Bob rule per role: which part of the source root's vertical motion gets
// baked as the pelvis position track (see Retargeter.bake).
const BOB_RULE = {
  'loop':           'full',
  'idle-loop':      'full',
  'idle-break':     'full',
  // Full: a crouch enter/exit must reach (and leave) the true crouch depth, or
  // it pops into the deeper crouch loops it hands off to. These clips never
  // rise against physics, so the unclosed track is safe.
  'transition':     'full',
  // Clamped to ≤ 0: take-offs squash into the jump and landings drop in from
  // high in the air — the rise and the fall belong to the controller, not the
  // clip, but the impact dip and the squat are real and get baked.
  'jump-start':     'crouch',
  'jump-land':      'crouch',
  'jump-land-special': 'crouch',
  // No track: the fall is pure physics.
  'jump-fall':      'none',
};

// Loaded first, so the character is up and idling while the rest streams in.
const PRIORITY_KEYS = ['idle_loop', 'walk_f', 'run_f', 'sprint_f', 'crouch_f', 'jump_fall'];

/** Strip armature/object prefix from FBX track names so they bind by bone name. */
function fixClipTracks(clip) {
  const fixed = clip.tracks.map(track => {
    let name = track.name;
    const pipe = name.indexOf('|');
    if (pipe !== -1) name = name.slice(pipe + 1);
    if (name === track.name) return track;
    const T = track.clone();
    T.name = name;
    return T;
  });
  return new THREE.AnimationClip(clip.name, clip.duration, fixed);
}

export class AnimationDatabase {
  constructor(manifest = CLIP_LIBRARY) {
    this.clips = new Map();   // key → THREE.AnimationClip (retargeted)
    this.manifest = manifest.entries;
    this.bobReference = manifest.pelvisBobReference ?? 0;
    this.refRig = null;       // one FBX scene, used as the retarget source rig
    this._entries = new Map(manifest.entries.map(e => [e.key, e]));
  }

  async load(onProgress) {
    const loader = new FBXLoader();
    let done = 0;
    const total = this.manifest.length;

    const loadOne = ({ key, path }) =>
      new Promise(resolve => {
        loader.load(
          path,
          obj => {
            if (obj.animations && obj.animations.length > 0) {
              // Every clip ships with the same rig; keep one copy as the
              // retarget source. It is never added to the scene.
              if (!this.refRig) this.refRig = obj;
              const clip = fixClipTracks(obj.animations[0]);
              clip.name = key;
              this.clips.set(key, clip);
            } else {
              console.warn(`[AnimationDatabase] no animation in ${path}`);
            }
            done++;
            onProgress?.(done, total);
            resolve();
          },
          undefined,
          err => {
            console.warn(`[AnimationDatabase] failed: ${path}`, err);
            done++;
            onProgress?.(done, total);
            resolve();
          }
        );
      });

    // Load priority clips first (idle + the forward gaits), then the rest.
    const prio = this.manifest.filter(m => PRIORITY_KEYS.includes(m.key));
    const rest = this.manifest.filter(m => !PRIORITY_KEYS.includes(m.key));

    await Promise.all(prio.map(loadOne));
    await Promise.all(rest.map(loadOne));
  }

  /**
   * Bake every loaded clip onto the target skeleton. Must run before the clips
   * are handed to a mixer, since the raw clips are bound to the source rig's
   * bone names and would otherwise resolve to nothing.
   */
  retarget(targetRoot, onProgress) {
    if (!this.refRig) {
      console.error('[AnimationDatabase] no reference rig — cannot retarget');
      return;
    }
    const rt = new Retargeter(this.refRig, targetRoot);
    let done = 0;
    const total = this.clips.size;

    for (const [key, clip] of [...this.clips]) {
      const entry = this._entries.get(key);
      const rule = BOB_RULE[entry?.role] ?? 'none';
      this.clips.set(key, rt.bake(clip, 30, {
        pelvisBob: rule,
        pelvisBobReference: this.bobReference,
      }));
      onProgress?.(++done, total);
    }

    rt.restoreRest();
    console.log(`[AnimationDatabase] retargeted ${total} clips`);
  }

  get(key) { return this.clips.get(key) ?? null; }

  /** The manifest entry for a key (features, meta, role), or null. */
  entryFor(key) { return this._entries.get(key) ?? null; }

  // All manifest entries that have a loaded clip.
  available() {
    return this.manifest.filter(m => this.clips.has(m.key));
  }
}
